apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: classrooms
        image: abdullahdaniyal1234/classrooms-service:latest
        ports:
        - containerPort: 2235
        env:
          - name: PORT
            value: "2235"
          - name: MONGO_URL
            value: "mongodb+srv://abdullahdaniyal:superflies2026@cluster0.s5b7diq.mongodb.net/scd-final"
---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
spec:
  selector:
    app: classrooms
  ports:
    - protocol: TCP
      port: 2235
      targetPort: 2235
  type: ClusterIP
