apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: eventbus
          image: abdullahdaniyal1234/eventbus-service:latest
          ports:
            - containerPort: 2236
          env:
            - name: PORT
              value: "2236"
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-service
spec:
  selector:
    app: eventbus
  ports:
    - protocol: TCP
      port: 2236
      targetPort: 2236
  type: ClusterIP
